export interface Project {
  slug: string;
  title: string;
  description: string;
  longDescription: {
    story: string;
    howItWorks: string;
    vision: string;
  };
  images: string[];
  videoId: string;
  tags: string[];
  github: string;
  demo: string;
  codeSnippet?: string;
  codeSnippetPosition?: 'top' | 'bottom';
}

export const projects: Project[] = [
  {
    slug: "ghumofiro",
    title: "GhumoFiro",
    description:
      "A travel itinerary web app featuring both manual and AI-powered trip planning, integrating SerpAI to fetch real flights, attractions, and activities for personalized travel recommendations.",
    longDescription: {
      story: "The idea stemmed from the frustration of scattered travel planning. Flight details on one site, hotels on another, and itinerary notes in a messy notepad. GhumoFiro solves this by unifying the entire experience.",
      howItWorks: "GhumoFiro mixes manual override with AI suggestions. Users can start with a prompt, get a full itinerary generated by Gemini, and then tweak every detail using real-time data from SerpAPI.",
      vision: "To become the ultimate travel companion that doesn't just plan trips but adapts to them in real-time."
    },
    images: [
      "/assets/projects/GhumoFiro/1.png",
      "/assets/projects/GhumoFiro/1.png",
      "/assets/projects/GhumoFiro/1.png",
    ],
    videoId: "",
    tags: ["Next.js", "Express", "Node", "MongoDB", "Firebase"],
    github: "https://github.com/Sambhav-3010/GhumoFiro",
    demo: "https://ghumofiro.vercel.app",
    codeSnippet: `const getFlightData = async (source, destination, date) => {
  try {
    const response = await axios.get('https://serpapi.com/search', {
      params: {
        engine: "google_flights",
        departure_id: source,
        arrival_id: destination,
        outbound_date: date,
        api_key: process.env.SERP_API_KEY
      }
    });
    return response.data.flights;
  } catch (error) {
    console.error("Error fetching flights:", error);
    return [];
  }
};`,
  },
  {
    slug: "propchain",
    title: "PropChain",
    description:
      "A decentralized land registry platform using smart contracts for secure property transactions. Integrated Web3 with Next for blockchain-based ownership verification and transfers.",
    longDescription: {
      story: "Property fraud and opaque transactions are major issues in real estate. PropChain was built to bring transparency and trust back into the system using the immutability of blockchain.",
      howItWorks: "Properties are tokenized as NFTs. Smart contracts handle the transfer of ownership, ensuring that funds are only released when the title is successfully transferred.",
      vision: "A world where property ownership is as seamless and secure as sending an email."
    },
    images: [
      "/assets/projects/PropChain/1.png",
      "/assets/projects/PropChain/1.png",
      "/assets/projects/PropChain/1.png",
    ],
    videoId: "",
    tags: ["Next.js", "Express", "MongoDB", "Firebase", "Ethereum", "Solidity"],
    github: "https://github.com/Sambhav-3010/PropChain",
    demo: "https://nfc-prop-chain.vercel.app",
    codeSnippet: `contract LandRegistry {
    struct Property {
        uint256 id;
        string location;
        address owner;
        bool forSale;
        uint256 price;
    }
    
    mapping(uint256 => Property) public properties;
    
    function transferOwnership(uint256 _id, address _newOwner) public {
        require(msg.sender == properties[_id].owner, "Only owner can transfer");
        properties[_id].owner = _newOwner;
    }
}`,
  },
  {
    slug: "settlemate",
    title: "SettleMate",
    description:
      "Expense splitting application with a visual analytics dashboard and QR-based UPI payments, enabling users to track expenses, analyze spending patterns, and settle dues instantly via scannable payment codes.",
    longDescription: {
      story: "Splitting bills with roomates should not be a math homework. SettleMate makes it instant, visual, and fair.",
      howItWorks: "Groups are created, expenses are added, and the optimal settlement strategy is calculated to minimize the number of transactions required.",
      vision: "Frictionless financial interactions between friends."
    },
    images: [
      "/assets/projects/SettleMate/1.png",
      "/assets/projects/SettleMate/1.png",
      "/assets/projects/SettleMate/1.png",
    ],
    videoId: "",
    tags: ["Next.js", "Express", "Socket.io", "PrismaDB", "NeonDB"],
    github: "https://github.com/Sambhav-3010/SettleMate",
    demo: "https://settle-mates.vercel.app",
    codeSnippet: `io.on('connection', (socket) => {
  socket.on('join-room', (roomId) => {
    socket.join(roomId);
  });

  socket.on('add-expense', (data) => {
    // Process expense logic
    io.to(data.roomId).emit('expense-added', data);
  });
});`,
  },
  {
    slug: "quickweb-ai",
    title: "QuickWeb.ai",
    description: "An AI powered website generator using Qwen and Gemini 2.5 to transform simple prompts into fully structured, production-ready websites within seconds.",
    longDescription: {
      story: "Prototyping takes too long. QuickWeb.ai was created to go from idea to deployed website in seconds.",
      howItWorks: "An LLM chain analyzes the user prompt, generates the HTML/CSS/JS structure, and a secondary agent deploys it to a sandbox environment.",
      vision: "Democratizing web development for everyone."
    },
    images: [
      "/assets/projects/QuickWeb.ai/1.png",
      "/assets/projects/QuickWeb.ai/1.png",
      "/assets/projects/QuickWeb.ai/1.png",
    ],
    videoId: "",
    tags: ["Next.js", "Express", "Node", "TypeScript"],
    github: "https://github.com/Sambhav-3010/QuickWeb.ai",
    demo: "https://quickwebai.vercel.app",
    codeSnippet: `async function generateWebsite(prompt) {
  const llmResponse = await llm.generate(
    "Create a website based on: " + prompt + ". Return JSON with html, css, and js fields."
  );
  
  const parsed = JSON.parse(llmResponse);
  return await deployToVercel(parsed);
}`,
  },
]
